# 使用iris（鸢尾花）数据集进行分类练习

In [2]:
#导入iris数据集
from sklearn.datasets import load_iris 
data = load_iris()
data

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [86]:
X,y,target = data['data'],data['target'],data['target_names']
X,y

(array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
        [5

In [77]:
import pandas as pd

In [85]:
df = pd.DataFrame({'X':X.tolist(),'y':y.tolist()})
df

X  y
0    [5.1, 3.5, 1.4, 0.2]  0
1    [4.9, 3.0, 1.4, 0.2]  0
2    [4.7, 3.2, 1.3, 0.2]  0
3    [4.6, 3.1, 1.5, 0.2]  0
4    [5.0, 3.6, 1.4, 0.2]  0
5    [5.4, 3.9, 1.7, 0.4]  0
6    [4.6, 3.4, 1.4, 0.3]  0
7    [5.0, 3.4, 1.5, 0.2]  0
8    [4.4, 2.9, 1.4, 0.2]  0
9    [4.9, 3.1, 1.5, 0.1]  0
10   [5.4, 3.7, 1.5, 0.2]  0
11   [4.8, 3.4, 1.6, 0.2]  0
12   [4.8, 3.0, 1.4, 0.1]  0
13   [4.3, 3.0, 1.1, 0.1]  0
14   [5.8, 4.0, 1.2, 0.2]  0
15   [5.7, 4.4, 1.5, 0.4]  0
16   [5.4, 3.9, 1.3, 0.4]  0
17   [5.1, 3.5, 1.4, 0.3]  0
18   [5.7, 3.8, 1.7, 0.3]  0
19   [5.1, 3.8, 1.5, 0.3]  0
20   [5.4, 3.4, 1.7, 0.2]  0
21   [5.1, 3.7, 1.5, 0.4]  0
22   [4.6, 3.6, 1.0, 0.2]  0
23   [5.1, 3.3, 1.7, 0.5]  0
24   [4.8, 3.4, 1.9, 0.2]  0
25   [5.0, 3.0, 1.6, 0.2]  0
26   [5.0, 3.4, 1.6, 0.4]  0
27   [5.2, 3.5, 1.5, 0.2]  0
28   [5.2, 3.4, 1.4, 0.2]  0
29   [4.7, 3.2, 1.6, 0.2]  0
..                    ... ..
120  [6.9, 3.2, 5.7, 2.3]  2
121  [5.6, 2.8, 4.9, 2.0]  2
122  [7.7, 2.8, 6.7, 2.0]  2
123  [6.3, 2.7, 4.9, 1.8]  2
124  [6.7, 3.3, 5.7, 2.1]  2
125  [7.2, 3.2, 6.0, 1.8]  2
126  [6.2, 2.8, 4.8, 1.8]  2
127  [6.1, 3.0, 4.9, 1.8]  2
128  [6.4, 2.8, 5.6, 2.1]  2
129  [7.2, 3.0, 5.8, 1.6]  2
130  [7.4, 2.8, 6.1, 1.9]  2
131  [7.9, 3.8, 6.4, 2.0]  2
132  [6.4, 2.8, 5.6, 2.2]  2
133  [6.3, 2.8, 5.1, 1.5]  2
134  [6.1, 2.6, 5.6, 1.4]  2
135  [7.7, 3.0, 6.1, 2.3]  2
136  [6.3, 3.4, 5.6, 2.4]  2
137  [6.4, 3.1, 5.5, 1.8]  2
138  [6.0, 3.0, 4.8, 1.8]  2
139  [6.9, 3.1, 5.4, 2.1]  2
140  [6.7, 3.1, 5.6, 2.4]  2
141  [6.9, 3.1, 5.1, 2.3]  2
142  [5.8, 2.7, 5.1, 1.9]  2
143  [6.8, 3.2, 5.9, 2.3]  2
144  [6.7, 3.3, 5.7, 2.5]  2
145  [6.7, 3.0, 5.2, 2.3]  2
146  [6.3, 2.5, 5.0, 1.9]  2
147  [6.5, 3.0, 5.2, 2.0]  2
148  [6.2, 3.4, 5.4, 2.3]  2
149  [5.9, 3.0, 5.1, 1.8]  2

[150 rows x 2 columns]

In [7]:
#将数据集随机分成训练数据和测试数据
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.33, random_state=42)

In [8]:
X_train

array([[5.7, 2.9, 4.2, 1.3],
       [7.6, 3. , 6.6, 2.1],
       [5.6, 3. , 4.5, 1.5],
       [5.1, 3.5, 1.4, 0.2],
       [7.7, 2.8, 6.7, 2. ],
       [5.8, 2.7, 4.1, 1. ],
       [5.2, 3.4, 1.4, 0.2],
       [5. , 3.5, 1.3, 0.3],
       [5.1, 3.8, 1.9, 0.4],
       [5. , 2. , 3.5, 1. ],
       [6.3, 2.7, 4.9, 1.8],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [5.6, 2.7, 4.2, 1.3],
       [5.1, 3.4, 1.5, 0.2],
       [5.7, 3. , 4.2, 1.2],
       [7.7, 3.8, 6.7, 2.2],
       [4.6, 3.2, 1.4, 0.2],
       [6.2, 2.9, 4.3, 1.3],
       [5.7, 2.5, 5. , 2. ],
       [5.5, 4.2, 1.4, 0.2],
       [6. , 3. , 4.8, 1.8],
       [5.8, 2.7, 5.1, 1.9],
       [6. , 2.2, 4. , 1. ],
       [5.4, 3. , 4.5, 1.5],
       [6.2, 3.4, 5.4, 2.3],
       [5.5, 2.3, 4. , 1.3],
       [5.4, 3.9, 1.7, 0.4],
       [5. , 2.3, 3.3, 1. ],
       [6.4, 2.7, 5.3, 1.9],
       [5. , 3.3, 1.4, 0.2],
       [5. , 3.2, 1.2, 0.2],
       [5.5, 2.4, 3.8, 1.1],
       [6.7, 3

In [9]:
y_train

array([1, 2, 1, 0, 2, 1, 0, 0, 0, 1, 2, 0, 0, 0, 1, 0, 1, 2, 0, 1, 2, 0,
       2, 2, 1, 1, 2, 1, 0, 1, 2, 0, 0, 1, 1, 0, 2, 0, 0, 1, 1, 2, 1, 2,
       2, 1, 0, 0, 2, 2, 0, 0, 0, 1, 2, 0, 2, 2, 0, 1, 1, 2, 1, 2, 0, 2,
       1, 2, 1, 1, 1, 0, 1, 1, 0, 1, 2, 2, 0, 1, 2, 2, 0, 2, 0, 1, 2, 2,
       1, 2, 1, 1, 2, 2, 0, 1, 2, 0, 1, 2])

In [10]:
X_test

array([[6.1, 2.8, 4.7, 1.2],
       [5.7, 3.8, 1.7, 0.3],
       [7.7, 2.6, 6.9, 2.3],
       [6. , 2.9, 4.5, 1.5],
       [6.8, 2.8, 4.8, 1.4],
       [5.4, 3.4, 1.5, 0.4],
       [5.6, 2.9, 3.6, 1.3],
       [6.9, 3.1, 5.1, 2.3],
       [6.2, 2.2, 4.5, 1.5],
       [5.8, 2.7, 3.9, 1.2],
       [6.5, 3.2, 5.1, 2. ],
       [4.8, 3. , 1.4, 0.1],
       [5.5, 3.5, 1.3, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.1, 3.8, 1.5, 0.3],
       [6.3, 3.3, 4.7, 1.6],
       [6.5, 3. , 5.8, 2.2],
       [5.6, 2.5, 3.9, 1.1],
       [5.7, 2.8, 4.5, 1.3],
       [6.4, 2.8, 5.6, 2.2],
       [4.7, 3.2, 1.6, 0.2],
       [6.1, 3. , 4.9, 1.8],
       [5. , 3.4, 1.6, 0.4],
       [6.4, 2.8, 5.6, 2.1],
       [7.9, 3.8, 6.4, 2. ],
       [6.7, 3. , 5.2, 2.3],
       [6.7, 2.5, 5.8, 1.8],
       [6.8, 3.2, 5.9, 2.3],
       [4.8, 3. , 1.4, 0.3],
       [4.8, 3.1, 1.6, 0.2],
       [4.6, 3.6, 1. , 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [6.7, 3.1, 4.4, 1.4],
       [4.8, 3.4, 1.6, 0.2],
       [4.4, 3

In [11]:
y_test

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 2, 2, 1, 2])

In [144]:
#调用 knn 模型的 KNeighborsClassifier类
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=11) #n_neighbors 就是 k 个点，取距离最近的11个点，即 K = 25（可调整）

In [145]:
knn.fit(X_train,y_train) #用  fit 方法对训练数据进行学习

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=11, p=2,
                     weights='uniform')

In [114]:
import numpy as np
import random

In [146]:
#随机生成新数据进行测试
#X_new = np.random.rand(1,4)*10
X_new = np.random.randint(1,10,(1,4))
X_new

array([[2, 6, 2, 6]])

In [147]:
# 用predict方法对新数据进行分类预测
prediction = knn.predict(X_new)

#预测结果
print("Predicted target name : {}".format(target[prediction]))
prediction

Predicted target name : ['setosa']


array([0])

In [148]:
#用测试数据对模型的准确性进行评估，准确率为100%。准确率与 k 的个数有关，k点的个数越多，准确率越高。
y_predict = knn.predict(X_test)

print(np.mean(y_predict == y_test))

1.0
